### ISSUE TITLE
username & password

### ISSUE THREAD

**Issue by mehransat** [amirmbn/WireGuard-Dashboard#1]
سلام.وقت بخیر
با یوزرنیم و پسوورد admin وارد نمی شود و  این پیام را نمایش می دهد: 
نام کاربری یا کلمه عبور اشتباه است.

**Comment by amirmbn** [comment]
درود، لطفا پسورد را 1234 وارد کنید

**Comment by amirmbn** [comment]
درود، رمزعبور را 1234 وارد کنید.
موفق باشید
