### ISSUE TITLE
پنل

### ISSUE THREAD

**Issue by proxystore11** [amirmbn/WireGuard-Dashboard#2]
سلام پنل بالا نمیاد دوبار ریبوت کردم باز دستور ریستارت زدم و ریبیلد هم کردم مراحلو دوباره جلو رفتم 
سرور از هتزنر و اوبنتو 22

**Comment by amirmbn** [comment]
درود بر شما
حتما یکی از مراحل رو درست انجام ندادید
لطفا پروژه را با دقت مطالعه و تمام مراحل را با دقت بیشتر پیش ببرید

**Comment by arminmacx** [comment]
> سلام پنل بالا نمیاد دوبار ریبوت کردم باز دستور ریستارت زدم و ریبیلد هم کردم مراحلو دوباره جلو رفتم سرور از هتزنر و اوبنتو 22

منم همین مشکل رو دارم و مو به مو طبق آموزش رفتم ولی همچنان این مشکل هست

**Comment by amirmbn** [comment]
حتما اینترفیس رو بررسی کنید، امکان اینکه دیتاسنتر ایران شما آی پی خارج رو فیلتر کرده باشه و یا آی پی شما کلا فیلتر باشه زیاده. (این مشکل بیشتر در دیتاسنتر های ابری/Cloud پیش میاد)

سرور ایران و خارج رو عوض کنید

**Comment by arminmacx** [comment]
> حتما اینترفیس رو بررسی کنید، امکان اینکه دیتاسنتر ایران شما آی پی خارج رو فیلتر کرده باشه و یا آی پی شما کلا فیلتر باشه زیاده. (این مشکل بیشتر در دیتاسنتر های ابری/Cloud پیش میاد)
> 
> سرور ایران و خارج رو عوض کنید

من سرور تازه ساختم و ایپی تمیز هست و فعلا وصلش نکردم به سرور ایران فقط نصب کردم مستقیم بهش وصل بشم که فعلا همین مشکل هست.
پنل یوزر و پسورد میاد تا میزنی اررو میده

**Comment by amirmbn** [comment]
حتما یک بخش رو اشتباه انجام دادید، لطفا مراحل رو دقیق و با دقت پیش ببرید
