### ISSUE TITLE
تاریخ اکانت ها

### ISSUE THREAD

**Issue by reza2450** [amirmbn/WireGuard-Dashboard#3]
سلا م ودرود خدمت شما عزیز خسته نباشید 
مشکل عدم تنظیم زمان برای کاربر ها بعد از یه مدتی رخ میده اگر زمان داشتید بررسی کنید ممنون از شما

**Comment by amirmbn** [comment]
لطفا توضیحات رو به طور کامل با نمونه تصویر در تلگرام ارسال کنید

**Comment by amirmbn** [comment]
> سلا م ودرود خدمت شما عزیز خسته نباشید مشکل عدم تنظیم زمان برای کاربر ها بعد از یه مدتی رخ میده اگر زمان داشتید بررسی کنید ممنون از شما


لطفا توضیحات رو به طور کامل با نمونه تصویر در تلگرام ارسال کنید
