### ISSUE TITLE
تنظیم پورت و Ip

### ISSUE THREAD

**Issue by hosseini2024** [amirmbn/WireGuard-Dashboard#4]
سلام 
وقت بخیر

اولا تشکر از زحمت شما دمتون گرم ❤️

میخواستم بدونم چرا وقتی تو بخش تنظیمات پنل ip و پورت رو عوض میکنم دیگه پنل کلا بالا نمیاد !! 
امکانش هست از تو سرور تنظیمات پنل رو ریست زد ؟ 🤔

دوبار مراحل نصب رفتم که بتونم از اول وارد بشم ولی نشد، 
چون فکر یک بار نصب کرده بودم  نشد نمیدونم چطور باید چیزهای که نصب کردم کلا از سرور پاک کنم 

ممنون میشم راهنمای کنید چیکار باید کنم ؟

**Comment by amirmbn** [comment]
> سلام وقت بخیر
> 
> اولا تشکر از زحمت شما دمتون گرم ❤️
> 
> میخواستم بدونم چرا وقتی تو بخش تنظیمات پنل ip و پورت رو عوض میکنم دیگه پنل کلا بالا نمیاد !! امکانش هست از تو سرور تنظیمات پنل رو ریست زد ؟ 🤔
> 
> دوبار مراحل نصب رفتم که بتونم از اول وارد بشم ولی نشد، چون فکر یک بار نصب کرده بودم نشد نمیدونم چطور باید چیزهای که نصب کردم کلا از سرور پاک کنم
> 
> ممنون میشم راهنمای کنید چیکار باید کنم ؟

شما داخل بخش تنظیمات / تنظیمات پنل قسمت آیپی پنل رو عوض کردید ؟؟

**Comment by hosseini2024** [comment]
> > سلام وقت بخیر
> > اولا تشکر از زحمت شما دمتون گرم ❤️
> > میخواستم بدونم چرا وقتی تو بخش کنترل پنل ip و پورت رو عوض میکنم دیگه پنل کلا بالا نمیاد !! امکانش هست از تو سرور پنل رو ریست زد ؟ 🤔
> > دوبار مراحل نصب رفتم که بتونم از اول وارد بشم ولی نشد، چون فکر یک بار نصب کردم نمی دونم چطور باید چیزهایی که نصب کردم کلا از سرور پاک کنم.
> > ممنون میشم راهنمایی کنید چیکار باید کنم ؟
> 
> شما داخل منطقه / نقطه پنل قسمت آیپی پنل رو عوض کردید ؟؟

رو دوتا سرور انجام دادم
یکی رو هم اip سرورم گذاشتم هم پورت عوض کردم

یکی دیگه رو فقط پورتش عوض کردم
و قسمت ip تغییر ندادم

هر دو سرور پنلش بالا نمیاد

**Comment by hosseini2024** [comment]
اگر نمیشه تنظیمات ریست کرد
یه راه بگین بتونم پنل وایرگارد از رو سرور حذف کنم تا دوباره نصبش کنم 

نمیتونم سرور خام کنم چون روش پنل سنایی دارم

**Comment by amirmbn** [comment]
> > > سلام وقت بخیر
> 
> > > اولا تشکر از زحمت شما دمتون گرم ❤️
> 
> > > میخواستم بدونم چرا وقتی تو بخش کنترل پنل ip و پورت رو عوض میکنم دیگه پنل کلا بالا نمیاد !! امکانش هست از تو سرور پنل رو ریست زد ؟ 🤔
> 
> > > دوبار مراحل نصب رفتم که بتونم از اول وارد بشم ولی نشد، چون فکر یک بار نصب کردم نمی دونم چطور باید چیزهایی که نصب کردم کلا از سرور پاک کنم.
> 
> > > ممنون میشم راهنمایی کنید چیکار باید کنم ؟
> 
> > 
> 
> > شما داخل منطقه / نقطه پنل قسمت آیپی پنل رو عوض کردید ؟؟
> 
> 
> 
> رو دوتا سرور انجام دادم
> 
> یکی رو هم اip سرورم گذاشتم هم پورت عوض کردم
> 
> 
> 
> یکی دیگه رو فقط پورتش عوض کردم
> 
> و قسمت ip تغییر ندادم
> 
> 
> 
> هر دو سرور پنلش بالا نمیاد

شما اعلام قرمز زنگ زیرش رو خوندی؟؟

**Comment by hosseini2024** [comment]
> > > > سلام وقت بخیر
> > 
> > 
> > > > اولا تشکر از زحمت شما دمتون گرم ❤️
> > 
> > 
> > > > میخواستم بدونم چرا وقتی تو بخش کنترل پنل ip و پورت رو عوض میکنم دیگه پنل کلا بالا نمیاد !! امکانش هست از تو سرور پنل رو ریست زد ؟ 🤔
> > 
> > 
> > > > دوبار مراحل نصب رفتم که بتونم از اول وارد بشم ولی نشد، چون فکر یک بار نصب کردم نمی دونم چطور باید چیزهایی که نصب کردم کلا از سرور پاک کنم.
> > 
> > 
> > > > ممنون میشم راهنمایی کنید چیکار باید کنم ؟
> > 
> > 
> > > 
> > 
> > 
> > > شما داخل منطقه / نقطه پنل قسمت آیپی پنل رو عوض کردید ؟؟
> > 
> > 
> > رو دوتا سرور انجام دادم
> > یکی رو هم اip سرورم گذاشتم هم پورت عوض کردم
> > یکی دیگه رو فقط پورتش عوض کردم
> > و قسمت ip تغییر ندادم
> > هر دو سرور پنلش بالا نمیاد
> 
> شما اعلام قرمز زنگ زیرش رو خوندی؟؟

بله 
با همون ای پی سرور کانفینگ هم داشتم ، میخواستم با همون ای پی به پنل متصل بشه که دیدم جواب نداد اصلا

بعلاوه رو سرور دوم ای پی رو تغییر ندادم فقط پورت عوض کردم که اون هم مثل سرور اول بالا نمیاد

**Comment by amirmbn** [comment]
> اگر نمیشه تنظیمات ریست کرد یه راه بگین بتونم پنل وایرگارد از رو سرور حذف کنم تا دوباره نصبش کنم
> 
> نمیتونم سرور خام کنم چون روش پنل سنایی دارم

کد لازم برای حذف پنل را در انتهای پروژه گذاشتم

**Comment by hosseini2024** [comment]
دم شما گرم 🌹
فقط اگر دوباره پورت 1000 رو تغییر بدم مشکلی پیش نمیاد ؟
