### ISSUE TITLE
بکاپ 

### ISSUE THREAD

**Issue by hosseini2024** [amirmbn/WireGuard-Dashboard#5]
سلام 
امکانش هست تو پنل از کانفینگ های بکاپ گرفته بشه ؟

**Comment by amirmbn** [comment]
درود، خیر

**Comment by hosseini2024** [comment]
آیا قصد دارید پنل رو آپدیت کنید ؟

**Comment by amirmbn** [comment]
فعلا خیر، شاید در ماه های آینده

**Comment by hosseini2024** [comment]
زمانی که میخوام کانفینگ رو ادیت کنم مثلا اسمش رو عوض کنم یا زمان اشتراک رو تغییر بدم ، وقتی ذخیر رو میزنم صفحه هنگ میکنه و تغییرات اعمال نمیشه 

ممنون میشم یه آپدیت بدین 🙏

همه بکاپ ضروریه 
هم این مورد

**Comment by hosseini2024** [comment]
![Screenshot 2024-10-09 201003](https://github.com/user-attachments/assets/aab3d9f9-7683-4602-9d0f-16f1bcbe3796)
