### ISSUE TITLE
درخواست API

### ISSUE THREAD

**Issue by rbsdotnet** [amirmbn/WireGuard-Dashboard#6]
سلام دوست عزیز وقت بخیر
قبل از هرچیز باید بگم خداقوت کارت عالی عالی بود
دوست عزیز برای این پنل API هم هست؟
اگر خیر امکان نوشتن API برای این پنل هست؟

**Comment by amirmbn** [comment]
درود
خیر نیست، امکان نوشتن داره ولی من انجام نمیدم

**Comment by rbsdotnet** [comment]
با payton باید نوشته بشه؟
