### ISSUE TITLE
تانل Multiport

### ISSUE THREAD

**Issue by rbsdotnet** [amirmbn/WireGuard-Dashboard#7]
درود دوست عزیز
من از لینک شما برای تانل استفاده کردم فقط اینکه چه جوری میشه روی چند پورت تانل رو اجرا کرد؟

**Comment by Ten10vpn** [comment]
تانل بک هال بزن رفیق. میتونی مولتی پورتش کنی

**Comment by amirmbn** [comment]
شما در قسمتی که آدرس پورت میخواد میتونید برابر روش زیر پیش برید.
مثلا پورت های مد نظر شما 443 و 3400 و 4400 است
در قسمتی که از شما پورت رو میخواد به این شکل وارد کنید: 443,3400,4400 الان این سه پورت تانل شدن

**Comment by rbsdotnet** [comment]
برای پورت وایرگارد هم همین روش و انجام بدم؟

**Comment by amirmbn** [comment]
بله
